TEST('config files load and expose the split tables', function()
  Config = {}
  dofile('config/config.lua'); dofile('config/tracks.lua'); dofile('config/vehicles.lua')
  dofile('config/economy.lua'); dofile('config/pit.lua'); dofile('locales/en.lua')
  TRUTHY(Config.Checkpoints.Short_Track, 'tracks')
  EQ(#Config.Checkpoints.Long_Track, 5)
  TRUTHY(Config.PitCrewZones[1].coords, 'pit')
  EQ(Config.Economy.purseSource, 'society')
  EQ(Config.Economy.payouts[1], 5000)
  EQ(Config.Economy.poolSplit[1], 60)
  EQ(Config.Job.name, 'roxwoodracing')
  EQ(Config.Job.grades.director, 2)
  EQ(Config.Tune.Street.mods[11], 2)
  TRUTHY(Config.OpenClasses.Any, 'open classes')
  TRUTHY(#Config.SpecPresets.Super.vehicles > 0, 'presets')
  TRUTHY(Config.LocaleTable.mode_open, 'locale loaded')
end)

TEST('Locale substitutes numbered args and falls back to key', function()
  Config = { LocaleTable = { hello = 'Hi {1}, {2}' } }
  dofile('shared/locale.lua')
  EQ(Locale('hello', 'A', 'B'), 'Hi A, B')
  EQ(Locale('missing_key'), 'missing_key')
end)
